### ISSUE TITLE
Dial STI Review Letter proof run August 2019

### ISSUE THREAD

**Issue by SandyJane** [UpstreamDigital/SandyContent#8]
Kindly advise if you can please assist us with the correct link to the Saver Brochure on the Dialdirect website? From the email trail below you will see that the link on our review letters that direct to the Saver Policy Book / Brochure does not point to the correct destination on the website. It points to the BI Policy book. 

Even with this link https://www.dialdirect.co.za/brochures/saver/ it takes you to the BI Policy book. Will you be able to give us the correct link so that we can update it on the review letters?3

From Elize Swart

**Comment by Gabi16** [comment]
There is no Saver on DD
